name: Bot-Hosting.net Earn Coins

on:
  schedule:
    - cron: '0 23 * * *' # 每日23点（UTC时间）执行
  workflow_dispatch: # 允许手动触发

jobs:
  earn-coins:
    runs-on: ubuntu-latest

    steps:
    - name: 1. Checkout repository
      uses: actions/checkout@v2

    - name: 2. Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'  # 选择你需要的 Python 版本

    - name: 3. Install dependencies
      run: |
        cd ".github/scripts/earn-coins"
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: 4. Earn coins
      run: |
        python .github/scripts/earn-coins/earn-coins.py

    - name: 5. Discord notify
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      run: |
        DISCORD_WEBHOOK_MSG=$(cat discord-webhook-msg.json)
        curl -H "Content-Type: application/json" -d "$DISCORD_WEBHOOK_MSG" $DISCORD_WEBHOOK

    - name: 6. Send heartbeat signal
      env:
        BETTERSTACK: ${{ secrets.BETTERSTACK }}
      run: |
        curl $BETTERSTACK